@VideoRenderService_HostAddress = http://localhost:5036

POST {{VideoRenderService_HostAddress}}/api/video-render
Content-Type: application/json

{
  "imageUrl": "https://example.com/product.jpg",
  "market": "a101",
  "durationSeconds": 10
}
